# @package _global_
callbacks:
  latest:
    enabled: true                     # save latest checkpoints
    every: 500_000                     # save latest every N samples
  eval_checkpoint:
    enabled: true                     # run eval + save best checkpoints
    every: 69_750_000                  # eval cadence in samples
    episodes: 10                     # target completed episodes
    min_steps: 10_000                # minimum total steps collected
    max_steps_per_episode: 50_000      # cap per episode (eval-only)
    deterministic: true               # imitation eval uses deterministic actions
    seed_offset: 10_000               # offset from run.seed for eval seeds
    mode: workers                  # vectorized | workers
#    n_envs: 1                        # eval env count (vectorized mode)
    workers: 8                        # parallel workers (workers mode)

learn:
  dataset_dir: datasets/bc/codemy2_uniform_noise  # dataset root (BC samples)
  epochs: 10                          # number of epochs over dataset
  batch_size: 512                     # batch size for BC updates
  learning_rate: 1.0e-4               # optimizer learning rate
  max_grad_norm: 1.0                  # gradient clipping norm
  shuffle: true                       # shuffle dataset each epoch
  max_samples: 0                      # max samples to use (0 = all)
  save_archive: true                  # archive final imitation checkpoint
  archive_dir: checkpoints/imitation  # directory for BC archives
  resume: null                        # optional: run dir or checkpoint path

algo:
  type: imitation                     # imitation
  params:
    policy_backend: maskable_ppo        # ppo | maskable_ppo
