# @package _group_
type: macro                     # MacroTetrisEnv (raw Dict obs only)
params:
  action_mode: discrete         # discrete | multidiscrete
  max_steps: none               # no truncation for eval/watch
  invalid_action_policy: noop   # noop | terminate

game:
  piece_rule: uniform           # uniform | bag7
  warmup: null                  # disable warmup for eval/watch
